/* TELE AULA 04 
### CONCEITOS ARRAYS E STRINGS EM JAVA
## ARRAYS 
-> A LINGUAGEM JAVA PERMITE A CRIAÇÃO DE ARRAYS UNIDIMENSIONAIS TAMBÉM CHAMADOS DE VETORES. 
-> UM VETOR AGRUPA UM CONJUNTO DE DADOS DE UM MESMO TIPO ORGANIZADOS EM LINHA OU COLUNA, E POR TRABALHAR COM DADOS DO MESMO TIPO, FALAMOS QUE O VETOR É UMA ESTRUTURA DE DADOS HOMOGÊNEA. 
-> A CRIAÇÃO E A MANIPULAÇÃO DE VETORES EM JAVA TÊM ALGUMAS SIMILARIDADES COM A LINGUAGEM C, MAS PARTE DA ALOCAÇÃO DE VETORES EM JAVA É MAIS SIMPLES QUE NA LINGUAGEM C, POIS NÃO É NECESSÁRIA A UTILIZAÇÃO DE COMANDOS COMO O MALLOC (ALOCAÇÃO DE MEMÓRIA). 
## INTRODUÇÃO A ARRAYS (VETOR) PARA POO 
-> UM ARRAY É UM GRUPO DE VARIÁVEIS (CHAMADOS ELEMENTOS OU COMPONENTES) QUE CONTÉM VALORES, TODOS DO MESMO TIPO. 
-> OS ELEMENTOS DE UM ARRAY PODEM SER TIPOS PRIMITIVOS OU TIPOS POR REFERÊNCIAS. 
-> O PRIMEIRO ELEMENTO DO ARRAY TEM ÍNDICE ZERO E ÀS VEZES É CHAMADO ZERO-ÉSIMO ELEMENTO.
-> UM ÍNDICE DEVE SER UMA VARIÁVEL DO TIPO INTEIRO, NÃO NEGATIVO.
-> OS ARRAYS SÃO OBJETOS E, POR ISSO, CONSIDERADOS TIPOS POR REFERÊNCIA. 
## VETOR UNIDIMENSIONAL 
# ARRAYS MULTIDIMENSIONAIS: MATRIZES 
-> A MATRIZ AGRUPA UM CONJUNTO DE DADOS DE UM MESMO TIPO ORGANIZADOS EM FORMA DE LINHAS E COLUNAS.
## INTRODUÇÃO A SEQUÊNCIAS DE CARACTERES PARA POO
-> POR MEIO DOS MÉTODOS DA CLASSE STRING, CONSEGUIMOS MANIPULAR CARACTERES E FAZER A INCLUSÃO DO NOME, DO GÊNERO E DO AUTOR DA MÚSICA.
-> STRING É UM ƟPO TEXTO QUE CORRESPONDE À UNIÃO DE UM CONJUNTO DE CARACTERES. EM JAVA, UMA VARIÁVEL DO TIPO STRING É UMA INSTÂNCIA DA CLASSE STRING, ISTO É, GERA OBJETOS QUE POSSUEM PROPRIEDADES E MÉTODOS, DIFERENTE DOS TIPOS PRIMITIVOS COMO INT, FLOAT, DOUBLE...
-> UMA SEQUÊNCIA DE CARACTERES É SEMPRE APRESENTADA ENTRE ASPAS.
# STRINGS
-> DA MESMA FORMA QUE OS ARRAYS, CADA ELEMENTO DE UMA STRING TAMBÉM É REFERENCIADO POR UM ÍNDICE QUE INDICA A POSIÇÃO DE DETERMINADO CARÁTER NA SEQUÊNCIA DE CARACTERES.
-> ESTE ÍNDICE PODE VALER ENTRE ZERO E O VALOR DO COMPRIMENTO DA STRING MENOS UM.
-> UM OBJETO DA CLASSE STRING NÃO PODERÁ SER ALTERADO DEPOIS DE CRIADO, JÁ QUE O JAVA NÃO OFERECE NENHUMA FUNCIONALIDADE QUE MUDE UMA SEQUÊNCIA DE CARACTERES;
-> NÃO HÁ NECESSIDADE DE ESPECIFICAR O TAMANHO (OU DIMENSÃO) DE UM OBJETO STRING NO ATO DA SUA CRIAÇÃO.
## APRESENTAÇÃO DA CLASSE STRING PARA POO 
-> EMBORA A CRIAÇÃO DE INSTÂNCIAS DA CLASSE STRING DISPENSE A CHAMADA DO CONSTRUTOR, OS OBJETOS AINDA ASSIM PODEM SER CRIADOS PELA FORMA USUAL, POR MEIO DO USO DA PALAVRA RESERVADA NEW EM CONJUNTO COM UM CONSTRUTOR QUE RECEBE COMO ARGUMENTO OUTRA INSTÂNCIA PREVIAMENTE CRIADA DA CLASSE STRING.
-> SANTOS (2003) NOS ENSINA QUE UMA INSTÂNCIA DE STRING TAMBÉM PODE SER CONSTRUÍDA USANDO A PASSAGEM DE UM ARRAY DE CARACTERES AO CONSTRUTOR.
# STRINGS
-> A LINGUAGEM JAVA POSSUI DUAS OUTRAS IMPORTANTES CLASSES QUE MANIPULAM STRINGS, QUE SÃO: A STRINGBUILDER E A STRINGBUFFER.
-> OS VALORES LITERAIS ARMAZENADOS NESSAS DUAS CLASSES SÃO MUTÁVEIS, OU SEJA, PODEM SER ALTERADOS A QUALQUER MOMENTO SEM QUE SEJA FEITA A CÓPIA DO LITERAL NA MEMÓRIA.
-> A CLASSE STRINGBUILDER É UMA BOA ALTERNATIVA À CLASSE STRING SE DESEJAR QUE O CONTEÚDO DA STRING SEJA MUTÁVEL. 
-> A CLASSE STRINGBUFFER É UMA BOA ALTERNATIVA ÀS OUTRAS DUAS CLASSES SE DESEJAR QUE O CONTEÚDO SEJA MUTÁVEL E NECESSITAR DE UMA APLICAÇÃO THREAD SAFE. DIZEMOS QUE UMA CLASSE É THREAD SAFE QUANDO DUAS OU MAIS THREADS NÃO PODEM INVOCAR MÉTODOS DESSA CLASSE SIMULTANEAMENTE.
# MEMÓRIAS HEAP E STRING POOL
-> TODA VEZ QUE CRIAMOS UM OBJETO COM O OPERADOR NEW, O OBJETO É COLOCADO NA HEAP, E TODA VEZ QUE CRIAMOS UM OBJETO LITERAL DIRETAMENTE (SEM O NEW), ESTE É COLOCADO NA STRING POOL.
-> A VANTAGEM DA STRING POOL SOBRE A HEAP É QUE ELA ECONOMIZA GASTOS COM MEMÓRIA.
## BANCOS DE DADOS RELACIONAL 
# CONCEITOS 
-> AS EMPRESAS NECESSITAM DE APLICAÇÕES COM MECANISMOS DE ARMAZENAMENTO DE DADOS, SEJAM SIMPLES COMO LEITURA DE TEXTO (.TXT), MANIPULAÇAO DE ARQUIVOS CSV OU INTEGRAÇÃO COM BANCO DE DADOS MAIS PODEROSO. UM BD PODE SER PENSADO COMO UMA FORMA DE ARMAZENAR E CONSULTAR DADOS, ASSIM, UM SIMPLES ARQUIVO PODE SER ENTENDIDO COMO UMA FORMA PRIMITIVA/SIMPLES DE SE MANTER OS DADOS. 
## LEITURA DE ARQUIVOS DE TEXTO 
-> DESEJAMOS CONSTRUIR UMA APLICAÇÃO QUE REALIZE A LEITURA E A IMPRESSÃO DE UM SIMPLES ARQUIVO DE TEXTO EM JAVA; A EXECUÇÃO DESSE CÓDIGO PRESSUPÕE QUE EXISTE UM ARQUIVO CHAMADO “POEMA.TXT” DENTRO DA PASTA “DADOS”.
## LEITURA DE ARQUIVOS CSV 
-> O ARQUIVO CSV, QUE POSSUI UM CONJUNTO DE VALORES SEPARADOS POR VÍRGULA OU ALGUM OUTRO DELIMITADOR EM SUA ORGANIZAÇÃO, COMO O PONTO E VÍRGULA, A TABULAÇÃO (TAB), O ESPAÇO, ENTRE OUTROS. UM ARQUIVO CSV É UM TIPO DE ARQUIVO DE TEXTO ESPECIAL, QUE PODE SER ABERTO POR QUALQUER EDITOR DE PLANILHA ELETRÔNICA, COMO EXCEL, CALC, GNUMERIC, ENTRE OUTROS. EXPERIMENTE ABRIR UM EDITOR DE TEXTO SIMPLES E DIGITAR O SEGUINTE CONTEÚDO: NOME, IDADE, PROFISSÃO, CIDADE, ESTADO ADRIANO, 56, ESCRITOR, RIO DE JANEIRO, RIO DE JANEIRO BARBARA, 34, MÉDICA, BELO HORIZONTE, MINAS GERAIS 
## BANCO DE DADOS 
-> OS BANCOS DE DADOS, GERALMENTE, UTILIZAM UMA LINGUAGEM DE CONSULTA, E A PRINCIPAL LINGUAGEM DE CONSULTA UTILIZADA É A SQL (STRUCTURED QUERY LANGUAGE OU LINGUAGEM DE CONSULTA ESTRUTURADA), QUE É UMA LINGUAGEM PADRÃO PARA ARMAZENAMENTO, MANIPULAÇÃO E RECUPERAÇÃO DE DADOS EM BD, QUE PODE SER UTILIZADA PARA TRABALHAR COM DIVERSOS BDS, COMO: MYSQL, MARIADB, MICROSOFT SQL SERVER, ORACLE, POSTGRESQL, ENTRE OUTROS
## APLICAÇÕES QUE UTILIZAM THREADS 
# PROCESSOS E THREADS 
-> AS THREADS SÃO UTILIZADAS PARA DESTRAVAR PARTE DA APLICAÇÃO QUANDO ALGUM PROCESSAMENTO PESADO ESTÁ SENDO EXECUTADO E ACELERAR O PROCESSAMENTO EM ALGUMA APLICAÇÃO QUE POSSA SER PARALELIZADA.
-> UM PROCESSO TEM O SEU PRÓPRIO AMBIENTE DE EXECUÇÃO E SEU PRÓPRIO ESPAÇO DE MEMÓRIA, ALÉM DISSO, É MUITO COMUM ASSOCIAR UM PROCESSO A UM PROGRAMA OU APLICAÇÃO, NO ENTANTO, ISSO NÃO É EXATAMENTE CORRETO E TAIS DETALHES SÃO ESTUDADOS NA DISCIPLINA DE SISTEMAS OPERACIONAL (SO).
-> UM PROCESSO COMO SENDO UMA APLICAÇÃO, SEM GRANDES PERDAS DE GENERALIDADE, POIS A MAIORIA DAS APLICAÇÕES EM JAVA RODA EM APENAS UM PROCESSO. 
-> UMA THREAD É UMA LINHA DE EXECUÇÃO; AO CRIARMOS UMA THREAD, ESTA CRIA TAMBÉM UM AMBIENTE DE EXECUÇÃO, MAS COMPARTILHA RECURSOS COMO MEMÓRIA E ARQUIVOS ABERTOS.
-> É IMPORTANTE QUE SAIBA QUE CADA PROCESSO TEM, PELO MENOS, UMA THREAD, MAS QUE É POSSÍVEL CRIAR MAIS THREADS DENTRO DESSE PROCESSO SE DESEJAR.
-> UM DOS ASPECTOS INTERESSANTES DAS THREADS É QUE PROCESSOS E THREADS
-> ELAS SÃO MAIS LEVES DO QUE OS PROCESSOS, E A EXECUÇÃO DE UMA THREAD PODE SER INTERROMPIDA QUANTAS VEZES FOREM NECESSÁRIAS, CONTINUANDO, SEMPRE, DO PONTO EM QUE PAROU.
-> É UMA TAREFA DO SO, EM ESPECÍFICO DO ESCALONADOR DE PROCESSOS, DECIDIR QUAL THREAD EXECUTARÁ E EM QUAL NÚCLEO DO PROCESSADOR. ESTADOS DE UMA THREAD DENTRO DO JAVA
*/