/* TELE AULA 03 - PARTE 03
# COMPARABLE, RUNNABLE E SERIALIZABLE. 
    -> COMPARABLE: 
        * É UTILIZADA PARA IMPOR UMA ORDEM NOS OBJETOS DE UMA DETERMINADA CLASSE QUE A IMPLEMENTA. 
        * PARA DEFINIR ESSA ORDEM, O MÉTODO COMPARETO DEVE SER IMPLEMENTADO, E NELE SERÃO ESTABELECIDOS OS CRITÉRIOS DA COMPARAÇÃO. 
        * UM VETOR OU UMA LISTA DE OBJETOS QUE IMPLEMENTA ESSA INTERFACE PODE SER ORDENADA AUTOMATICAMENTE POR MÉTODOS DE ORDENAÇÃO DISPONÍVEIS NO JAVA.
    -> RUNNABLE: 
        * É UTILIZADA PARA ESPECIFICAR ALGUMA TAREFA A SER REALIZADA. 
        * PARA SE DEFINIR ESSA TAREFA, O MÉTODO RUN DEVE SER IMPLEMENTADO, E NELE SERÁ ESTABELECIDA A TAREFA A SER EXECUTADA. 
        * DE FORMA GERAL, OS OBJETOS DESSA CLASSE SÃO EXECUTADOS EM PARALELO, UTILIZANDO-SE VÁRIAS THREADS.
    -> SERIALIZABLE: 
        * É UTILIZADA PARA IDENTIFICAR CLASSES EM QUE OS OBJETOS PODEM SER GRAVADOS (TAMBÉM CHAMADOS DE SERIALIZADOS) OU LIDOS (TAMBÉM CHAMADOS DE DESSERIALIZADOS) DE ALGUM DISPOSITIVO DE ARMAZENAMENTO, COMO HD. 
        * A INTERFACE SERIALIZABLE NÃO POSSUI MÉTODOS OU CAMPOS E SERVE APENAS PARA IDENTIFICAR A SEMÂNTICA DE SER SERIALIZÁVEL

# INTERFACES GRÁFICAS
    -> O JAVFX É UMA BIBLIOTECA MUITO BOA QUE A LINGUAGEM JAVA CONTA PARA A CONSTRUÇÃO DE APLICAÇÕES GRÁFICAS.
    -> A LINGUAGEM JAVA POSSUI UM SUPORTE MUITO BOM PARA A CRIAÇÃO DE INTERFACES GRÁFICAS DE USUÁRIO OU, EM INGLÊS, GRAPHICAL USER INTERFACE (GUI), E EXISTEM VÁRIAS FORMAS DE SE FAZER A CRIAÇÃO DE INTERFACES GRÁFICAS EM JAVA. 
    -> AO LONGO DA EVOLUÇÃO DESSA LINGUAGEM, DIVERSAS BIBLIOTECAS GRÁFICAS FORAM CRIADAS, COMO: 
        * ABSTRACT WINDOW TOOLKIT (AWT), SWING, STANDARD WIDGET TOOLKIT (SWT), APACHPIVOT, SWINGX, JGOODIES, QTJAM BI E JAVAFX.
*/

